export enum ActionTypes {
  CREATE_ORDER_START = 'CREATE_ORDER_START',
  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS',
  CREATE_ORDER_ERROR = 'CREATE_ORDER_ERROR',

  FETCH_ORDER_START = 'FETCH_ORDER_START',
  FETCH_ORDER_SUCCESS = 'FETCH_ORDER_SUCCESS',
  FETCH_ORDER_ERROR = 'FETCH_ORDER_ERROR',
}
