### login user
POST http://localhost:4000/auth/login
content-type: application/json

{
  "email": "john@example.com", 
  "password": "123456"
}

### getting current user 
GET http://localhost:4000/auth/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkpvaG4gRG9lIiwic3ViIjoiNjFkZTI0NjA0NDFjOWZjZjNlNjFkYjIwIiwiaWF0IjoxNjQyOTc3MDgwLCJleHAiOjE2NDMwNjM0ODB9.B7mU-3uh_Vlud-M14DvOBx8ptF589w1BUZIyRk6r4-w
