export const products = [
  {
    _id: '1',
    name: 'Airpods Wireless Bluetooth Headphones',
    image: '/images/airpods.webp',
    description:
      'Bluetooth technology lets you connect it with compatible devices wirelessly High-quality AAC audio offers immersive listening experience Built-in microphone allows you to take calls while working',
    brand: 'Apple',
    category: 'Electronics',
    price: 89.99,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
    reviews: [
      {
        name: 'Helen M.',
        rating: 5,
        comment: 'Excellent running shoes. It turns very sharply on the foot.',
        createdAt: '2024-03-19T10:00:00Z',
      },
      {
        name: 'Ann D.',
        rating: 4,
        comment: 'Good shoes',
        createdAt: '2024-03-17T15:30:00Z',
      },
      {
        name: 'Andrew G.',
        rating: 3,
        comment: 'Is it suitable for running?',
        createdAt: '2024-03-17T09:15:00Z',
      },
    ],
  },
  {
    _id: '2',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpeg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    reviews: [],
  },
  {
    _id: '3',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpeg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    reviews: [],
  },
  {
    _id: '4',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpeg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    reviews: [],
  },
  {
    _id: '5',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpeg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    reviews: [],
  },
  {
    _id: '6',
    name: 'iPhone 11 Pro 256GB Memory',
    image: '/images/phone.jpeg',
    description:
      'Introducing the iPhone 11 Pro. A transformative triple-camera system that adds tons of capability without complexity. An unprecedented leap in battery life',
    brand: 'Apple',
    category: 'Electronics',
    price: 599.99,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
    reviews: [],
  },
] as const;
