export enum ActionTypes {
  ADD_CART_ITEM_START = 'ADD_CART_ITEM_START',
  ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS',
  ADD_CART_ITEM_ERROR = 'ADD_CART_ITEM_ERROR',

  REMOVE_CART_ITEM_START = 'REMOVE_CART_ITEM_START',
  REMOVE_CART_ITEM_SUCCESS = 'REMOVE_CART_ITEM_SUCCESS',
  REMOVE_CART_ITEM_ERROR = 'REMOVE_CART_ITEM_ERROR ',

  FETCH_CART_ITEMS_START = 'FETCH_CART_ITEMS_START',
  FETCH_CART_ITEMS_SUCCESS = 'FETCH_CART_ITEMS_SUCCESS',
  FETCH_CART_ITEMS_ERROR = 'FETCH_CART_ITEMS_ERROR',
}
