export enum ActionTypes {
  ADD_CART_ITEM_START = 'ADD_CART_ITEM_START',
  ADD_CART_ITEM_SUCCESS = 'ADD_CART_ITEM_SUCCESS',
  ADD_CART_ITEM_ERROR = 'ADD_CART_ITEM_ERROR',

  REMOVE_CART_ITEM = 'REMOVE_CART_ITEM',

  GET_CART_ITEMS_START = 'GET_CART_ITEMS_START',
  GET_CART_ITEMS_SUCCESS = 'GET_CART_ITEMS_SUCCESS',
  GET_CART_ITEMS_ERROR = 'GET_CART_ITEMS_ERROR',
}
