export enum ActionTypes {
  USER_LOGIN_START = 'USER_LOGIN_START',
  USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS',
  USER_LOGIN_ERROR = 'USER_LOGIN_ERROR',

  GET_CURRENT_USER = 'GET_CURRENT_USER',
  USER_LOGOUT = 'USER_LOGOUT',
}
